baseURL = "https://xxxx.work/"
languageCode = "zh-cn"
title = "我的博客"
theme = "hugo-theme-stack"


mainSections = ["posts"]

[[menu.main]]
    name   = "首页"
    url    = "/"
    weight = -100
    [menu.main.params]
        icon = "home"

[[menu.main]]
    name   = "归档"
    url    = "/archives/"
    weight = -90
    [menu.main.params]
        icon = "archives"

[[menu.main]]
    name   = "关于"
    url    = "/about/"
    weight = -80
    [menu.main.params]
        icon = "user"
